//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooruDotNet.Danbooru.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Uris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooruDotNet.Danbooru.Resources.Uris", typeof(Uris).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://danbooru.donmai.us/posts.json?limit=1&amp;md5={0}.
        /// </summary>
        internal static string Danbooru_PostHash_Format {
            get {
                return ResourceManager.GetString("Danbooru_PostHash_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://danbooru.donmai.us/posts/{0}.json.
        /// </summary>
        internal static string Danbooru_PostId_Format {
            get {
                return ResourceManager.GetString("Danbooru_PostId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://danbooru.donmai.us/posts/{0}.
        /// </summary>
        internal static string Danbooru_PostUri_Format {
            get {
                return ResourceManager.GetString("Danbooru_PostUri_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://danbooru.donmai.us/tags.json?search[name_or_alias_matches]={0}.
        /// </summary>
        internal static string Danbooru_TagName_Format {
            get {
                return ResourceManager.GetString("Danbooru_TagName_Format", resourceCulture);
            }
        }
    }
}
